# Generated by Django 3.2.8 on 2022-09-27 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('root_link', models.URLField()),
                ('link', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='sheets/')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.field')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('fields', models.ManyToManyField(to='home.Field')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.university')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.university'),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.university')),
                ('fields', models.ManyToManyField(to='home.Field')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
