# Generated by Django 3.2.8 on 2022-05-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.field')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.university')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.university'),
        ),
    ]
