# Generated by Django 3.2.8 on 2022-05-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
        migrations.AddField(
            model_name='field',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
