# Generated by Django 3.2.8 on 2022-05-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220509_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
