# Generated by Django 3.2.8 on 2022-10-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_field_x_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='visitcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
