# Generated by Django 3.2.8 on 2022-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_field_visitcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='visitcount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
