# Generated by Django 3.2.8 on 2022-05-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='root_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
