# Generated by Django 3.2.8 on 2022-05-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_field_root_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='file',
            field=models.FileField(default=1, upload_to='sheets/'),
            preserve_default=False,
        ),
    ]
