# Generated by Django 3.2.8 on 2022-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_field_visitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='groups',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
