# Generated by Django 3.2.8 on 2022-05-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_field_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='field',
        ),
        migrations.AddField(
            model_name='group',
            name='field',
            field=models.ManyToManyField(to='home.Field'),
        ),
    ]
