# Generated by Django 3.2.8 on 2022-10-04 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_field_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
