# Generated by Django 3.2.8 on 2022-05-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220513_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='field',
            new_name='fields',
        ),
    ]
