# Generated by Django 3.2.8 on 2022-05-15 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_field_group_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('University', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.university')),
                ('fields', models.ManyToManyField(to='home.Field')),
            ],
        ),
    ]
