# Generated by Django 3.2.8 on 2022-05-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_faculty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AddField(
            model_name='field',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='degree',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='field',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='field',
            name='year',
            field=models.IntegerField(blank=True),
        ),
    ]
