# Generated by Django 3.2.8 on 2022-05-15 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220515_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='file',
            field=models.FileField(blank=True, upload_to='sheets/'),
        ),
        migrations.AlterField(
            model_name='field',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
