# Generated by Django 3.2.8 on 2022-05-15 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220515_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.field'),
        ),
    ]
